### ISSUE TITLE
[BUG] :lady_beetle: In Tarantool 3.x some indicators do not work

### ISSUE THREAD

**Issue by a1div0** [tarantool/grafana-dashboard#224]
Need to check:
* Cluster status overview
* Total instances running
* Not sure if this will be in every application: http_server_request_latency_count

![image](https://github.com/tarantool/grafana-dashboard/assets/4862582/04051f63-c0ac-4364-bee5-2cb06e3e451c)

**Comment by DifferentialOrange** [comment]
> Not sure if this will be in every application: http_server_request_latency_count

It applies to every panel. One may have vinyl metrics disabled, so vinyl panels would be empty. If application have never used http metrics middleware (or http at all), corresponding graphs would be empty for Cartridge application as well. And having both "Dashboard with HTTP panels" and "Dashboard without HTTP panels" published would result in hundreds of dashboard editions since we have ~20 metric sections. One may actually build their own dashboard without some section using tools provided by this repo.

On the other hand, cartridge-specific metrics (issues and failover) will always be empty for Tarantool 3 application. Status overview and instances count are based on the following assumption: metrics are pulled directly from each instance, which is not true for TCM approach. So I think a separate dashboard for Tarantool 3 + TCM is possible and should be built and published. On the other hand, I'm not sure that cluster overview panel could be re-created without some updates from TCM.

**Comment by DifferentialOrange** [comment]
For now, we think that cartridge issues should be reworked to use Tarantool 3 issues. We need metrics support first, and then we need to rework the panels.
