### ISSUE TITLE
"example" project is not helpful for beginners

### ISSUE THREAD

**Issue by olegrok** [tarantool/grafana-dashboard#63]
There is an example (https://github.com/tarantool/grafana-dashboard/tree/master/example) in our repo. It's not trivial to understand how does it works for person who first time run Grafana and Prometheus.

First of all, "project" application doesn't expose any metrics.

User need manually add to init.lua:
```lua
local metrics = require('cartridge.roles.metrics')
metrics.set_export({
    {
        path = '/metrics/prometheus',
        format = 'prometheus',
    }
})
```

Secondly it's not obvious how to install and run Prometheus and Graphana.
I think it's a lack of simple readme.md file that says:

```
brew install prometheus
brew install graphana
brew services start grafana # grafana will be available on :3000
prometheus --config.file="prometheus/prometheus.yml" # prometheus will be available on :9090
# Here we need to verify "Status" -> "Targets" page.
```

Also it's better to change target urls from "example_project:*" to "localhost:*" - because basically user will run application using `cartridge start` that starts applications on the localhost.

Please add `replicasets.yml` file to test project. It will help to avoid some excess actions from user - all we need to call `cartridge replicasets setup`.

Finally, it would be great to add a small description about steps how to import dashboard from grafana.com. It's easier if user understand that "job" option means. It wasn't so in my case and I spent some time to understand what's wrong.

**Comment by DifferentialOrange** [comment]
Thank you for your comments!

The example cluster was meant to be run with docker. There is a README section with short description https://github.com/tarantool/grafana-dashboard#experimental-cluster . If you use `docker-compose up`, it will start up containers and a network which will make up two configured and fully functional monitoring stacks connected to a Tarantool example app. Tarantool container is a container which runs luatest that starts up a cluster, configure it and send some requests to make up some load for graphs (https://github.com/tarantool/grafana-dashboard/tree/master/example/project/cluster). Metrics output is configured with clusterwide configuration with luatest, and that is the reason why we don't have `metrics.set_export` code for now. The other reason is that this cluster was introduced before `set_export` and there wasn't any obvious reasons why we should upgrade. The cluster runs with luatest instead of cartridge-cli because it was built before introduction of `replicasets.yml` and it was not convenient to works with cluster as I wanted to (for example, set up roles and replicasets automatically).

So if you want to use this example cluster to test only Grafana-related functionality, you can simply run `docker-compose up` and go to `localhost:3000` to set up some boards. You do not need to set up Prometheus or Tarantool metrics output. If you want to change example app code, you can change example app code in folders and, if needed, changed enabled roles or cluster topology here if you're familiar with luatest https://github.com/tarantool/grafana-dashboard/tree/master/example/project/cluster (you may need to run `docker-compose build --no-cache` to reload code if you're have started a cluster before). If you want to monitor some app that already runs and have exposed metrics on your localhost, you may also use docker containers (`Prometheus` + `Grafana`) but configure your instances host:port in `Prometheus` config.

The reason that configuration uses `example_project:` is also so we could run it with docker-compose (which build a network for containers) and it will set up without any manual configuration.

It was planned to migrate to using `cartridge-cli` instead of `luatest` (#34) someday to set up example cluster. Maybe it is the time. But I still plan to run in inside docker container for now. The main reason for example cluster is to create an environment in which it is convenient to develop a dashboard. You can call a single `docker-compose up` and then go to `localhost:3000` to check up your new panel. So we won't change target urls until something changes.

Finally, we have a documentation page on how to import a dashboard and set up parameters https://www.tarantool.io/en/doc/latest/book/monitoring/grafana_dashboard/ . I have a link in README, but it seems like it's easy to miss. And looks like it is still not obvious how to find a job from here.

I hope that I can use this issue to build up such a README so its crucial points will be hard to miss.
